option("EXP_NUM")
    set_default("11")
    set_showmenu(true)
    set_category("prog/la32r_func")
    set_description("EXP n=?")

target("la32r_func")
    set_kind("phony")
    add_options("EXP_NUM")
    on_build(function (target)
        -- print("%s $(EXP_NUM)", target:scriptdir())
        os.cd(target:scriptdir())
        -- print(get_config("EXP_NUM"))
        os.exec("make buildexp EXP=$(EXP_NUM)")
    end)